#version 460
#extension GL_EXT_ray_tracing : require

layout(location = 0) rayPayloadEXT vec3 hitColor;

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba8) uniform image2D outImage;

void main()
{
	const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
	const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
	vec2       d           = inUV * 2.0 - 1.0;

	vec3 origin    = vec3(d * 2.0, -1.0);
	vec3 direction = vec3(0.0, 0.0, 1.0);

	uint  flags = gl_RayFlagsOpaqueEXT;
	float tmin  = 0.001;
	float tmax  = 100.0;

	traceRayEXT(topLevelAS, flags, 0xFF, 0, 0, 0, origin, tmin, direction, tmax, 0);

	imageStore(outImage, ivec2(gl_LaunchIDEXT.xy), vec4(hitColor, 1.0));
}
